apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-kc0q
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-kc0q
    app.kubernetes.io/part-of: tkrw-pr712-0075-0050-app
  name: devfile-sample-kc0q
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-kc0q
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-kc0q
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0050-tenant/tkrw-pr712-0075-0050-app/devfile-sample-kc0q@sha256:f0b9d4cf874cd0e0f810f18b7e0c2b5991e3bb4b5c38863a1d7e9180c016a42d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
